# Generated by Django 4.2.6 on 2023-10-31 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('short_url', models.TextField()),
                ('view_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'link',
            },
        ),
    ]
