# Generated by Django 4.2.6 on 2023-11-05 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_linkmember'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linkmember',
            old_name='member',
            new_name='user',
        ),
    ]
